### ISSUE TITLE
Extract Citation Contexts

### ISSUE THREAD

**Issue by cmkumar87** [WING-NUS/Neural-ParsCit#10]
There is a popular feature request to extract 'citation context' that is text surrounding the citation marker in the article's full body text for each of the citation parsed in the References / Bibliography.

Source for Citation Context Extraction in ParsCit:
https://github.com/knmnyn/ParsCit/blob/master/lib/ParsCit/CitationContext.pm

**Comment by kylase** [comment]
This is out-of-scope for this module. We have some work done on this area by a student previously. Probably better to isolate the code by functions.

**Comment by cmkumar87** [comment]
It is not 'invalid'. It was a functionality of parscit. So it is a natural feature request in neural ParsCit. However if @knmnyn advises to abandon this feature, so be it as he is the creator of Parscit and hold all rights (defacto), though the original ParsCit is legally opensourse. I relinquish any association if at all there was/is to this neural ParsCit repository.

**Comment by knmnyn** [comment]
@cmkumar87 has good points but for now there are other priorities and we have current work towards replicating much of ParsCit's functionality into a toolkit.  So, agree to close for now.

**Comment by kylase** [comment]
It's better to file this at the lab level. Perhaps Prof. can leverage the Project feature in Github's Organisation to keep track of such requests.

**Comment by cmkumar87** [comment]
@knmnyn @kylase I have no stakes in your group's projects other than those we are explicitly talking about with relevant parties over email. It's your project. My reply was towards the 'dismissive' and 'incorrect' invalid label which questions my judgment on filing the issue. As said, I have resigned as a 'point of contact' for neural-parcit. I assumed the resignation was automatic due to release from NUS.
