### ISSUE TITLE
Missing web server dependencies in Dockerfile

### ISSUE THREAD

**Issue by rakeshkasinathan** [WING-NUS/Neural-ParsCit#19]
I have a issue while using the below command.
/var/www/html/Neural-ParsCit$ sudo docker run --rm -it -p 8000:8000 -e TIMEOUT=60 -v $(pwd):/usr/src --name np theano-gensim:latest /bin/bash
root@46ecc721bd85:/usr/src# gunicorn -b 0.0.0.0:8000 -w $NUM_WORKERS --timeout $TIMEOUT run_app:app
bash: gunicorn: command not found
root@46ecc721bd85:/usr/src# gunicorn -b 0.0.0.0:8080 -w $NUM_WORKERS --timeout $TIMEOUT run_app:app
bash: gunicorn: command not found

**Comment by kylase** [comment]
The docker image doesn't install the dependencies required for web server. Please add `pip install -r requirements/prod.txt` to the Dockerfile or run it in the container.

We are deprecating this version soon and not going to work on patching this.
