### ISSUE TITLE
Neural-ParsCit

### ISSUE THREAD

**Issue by rakeshkasinathan** [WING-NUS/Neural-ParsCit#20]
**While run the below command,**
./run.py --model_path models/neuralParsCit/ --pre_emb vectors_with_unk.kv --run file -i 05_Ref.txt -o output.text
**I got the below issues could you please suggest me what i have made wrong**
from: too many arguments
import: unable to open X server `' @ error/import.c/ImportImageCommand/364.
import: unable to open X server `' @ error/import.c/ImportImageCommand/364.
import: unable to open X server `' @ error/import.c/ImportImageCommand/364.
import: unable to open X server `' @ error/import.c/ImportImageCommand/364.
import: unable to open X server `' @ error/import.c/ImportImageCommand/364.
import: unable to open X server `' @ error/import.c/ImportImageCommand/364.
from: too many arguments
from: too many arguments
from: too many arguments
from: too many arguments
./run.py: line 12: $'\r': command not found
./run.py: line 13: $'\r': command not found
./run.py: line 14: syntax error near unexpected token `('
'/run.py: line 14: `optparser = optparse.OptionParser()

**Comment by kylase** [comment]
Please check your newline characters. This is probably not an bug.
