### ISSUE TITLE
Problem while Train the Model

### ISSUE THREAD

**Issue by rakeshkasinathan** [WING-NUS/Neural-ParsCit#22]
When i try to train the model i am facing the below issue, please help me to sort.

root@02dae0d0158a:/usr/src#  ./train.py --train train.txt --dev dev.txt --test test.txt
[INFO] 2019-03-27 06:05:13,617: Model location: ./models/lower=False,zeros=False,char_dim=25,char_lstm_dim=25,char_bidirect=True,word_dim=100,word_lstm_dim=100,word_bidirect=
True,pre_emb=,all_emb=False,cap_dim=0,crf=True,dropout=0.5,lr_method=sgd-lr_.005
Found 2 unique words (8 in total)
Found 8 unique characters
Found 2 unique named entity tags
[INFO] 2019-03-27 06:05:13,623: 8 / 0 / 0 sentences in train / dev / test.
[INFO] 2019-03-27 06:05:13,623: Saving the mappings to disk...
Traceback (most recent call last):
  File "./train.py", line 200, in <module>
    f_train, f_eval = model.build(**parameters)
  File "/usr/src/model.py", line 177, in build
    pretrained = self.load_word_embeddings(pre_emb)
  File "/usr/src/model.py", line 425, in load_word_embeddings
    raise IOError("{embeddings} cannot be found.".format(embeddings=embeddings))
IOError:  cannot be found.

**Comment by kylase** [comment]
Have you downloaded the word embeddings?

**Comment by rakeshkasinathan** [comment]
Yes i have downloaded and extract word embeddings.

**Comment by kylase** [comment]
You need to provide `--pre_emb` which is your location of the word embeddings.
