### ISSUE TITLE
Unable to train using own data

### ISSUE THREAD

**Issue by GrennanM** [WING-NUS/Neural-ParsCit#25]
Hi,

Thanks for all your great work with this tool. I am having an issue training Neural Parscit using my own training data.

I have downloaded the word embeddings from http://wing.comp.nus.edu.sg/~wing.nus/resources/NParsCit/vectors_with_unk.tar.gz and they are located under the main folder.

I am able to parse citations using the command line as described:  
<code>
./run.py --model_path models/neuralParsCit/ --pre_emb <vectors.bin> --run shell
</code>

From what I understand the training data should be in the following form with a blank line between citations:

M. author  
Fedoryszak, author  
Large title  
Scale title  
Citation title  
Matching title  
Using title  
Apache title  
Hadoop title  
in booktitle  
International booktitle  
etc.  

When I run  
<code>
./train.py --train train.txt --dev dev.txt --test test.txt
</code>  
I get the error  
<code>
raise IOError("{embeddings} cannot be found.".format(embeddings=embeddings))
</code>

I understand this is to do with not providing the location of the embeddings but when I run  
<code>./train.py --pre_emb vectors_with_unk.kv --train train.txt --dev dev.txt --test test.txt  
</code>
I get the error:  
<code>
Traceback (most recent call last):
  File "train.py", line 201, in <module>
    f_train, f_eval = model.build(**parameters)
  File "/Neural-ParsCit/model.py", line 208, in build
    new_weights[i] = pretrained[word]
ValueError: could not broadcast input array from shape (500) into shape (100)
</code>  

Any help greatly appreciated.

**Comment by kylase** [comment]
Thanks @GrennanM.

Please refer to the command line parser (https://github.com/WING-NUS/Neural-ParsCit/blob/master/train.py#L56-L59), if you do not pass in any argument, the default `word_dim` is 100. The pretrained word embeddings we provide is 500 dimensions and hence you are unable to load the embedding.

**Comment by GrennanM** [comment]
Thanks @kylase ! That worked. 

Would you be able to tell me what the system requirements are for training? Unfortunately I'm getting a memory error now.

**Comment by kylase** [comment]
16 GB should be more than sufficient.

**Comment by GrennanM** [comment]
Thank you! And am I correct in the format of the training data? Or should punctuation be given on a separate line?

Should it be:
M. author
Fedoryszak, author
etc.

or...
M author
. author
Fedoryszak author
, author
etc.

Thanks again.

**Comment by kylase** [comment]
It should be compliant to Cora (McCallum, 2000).
