### ISSUE TITLE
Where is vectors.bin?

### ISSUE THREAD

**Issue by jasonwebb2455** [WING-NUS/Neural-ParsCit#27]
I have built the docker image and am running the container interactively, but I don't have the vectors.bin file necessary to use the state-of-the-art model that is saved to the repository. The Readme says that the vectors.bin file is in the docker image, but does that mean when I run the session interactively I should see vectors.bin, or does that mean I need to pull from some other docker image because the Dockerfile is not referencing anything I would believe has the vectors.bin file.

**Comment by kylase** [comment]
May I know which part of the README mentioned about the vectors.bin?

**Comment by Ranper** [comment]
I also have this problem. Have you solved it?

**Comment by kylase** [comment]
You can download the word embeddings from the link described in the [Word Embedding](https://github.com/WING-NUS/Neural-ParsCit/blob/master/README.md#embeddings-without-unk) section. It is a `KeyedVector` and not a `.bin` file to reduce the memory footprint.
