### ISSUE TITLE
Can we use neural parscit to parse .pdf documents?

### ISSUE THREAD

**Issue by bharathgit956** [WING-NUS/Neural-ParsCit#28]
I have a list of academic documents in the .pdf format. I want to extract citations from these documents. However, I am wondering whether we can use neural parscit for the .pdf documents. If yes, how can we use neural parscit on the .pdf files?

**Comment by animeshprasad** [comment]
Not yet. You would need parsCit to parse pdf, which in fact takes a pdfbox xml output and tags it in various scientific document sections. Neural ParsCit only parses the reference section taking text as input and producing the tagged output.
