### ISSUE TITLE
training data

### ISSUE THREAD

**Issue by NLPOR** [WING-NUS/Neural-ParsCit#29]
Great work, Could you please share the training corpus and test corpus in your experiment? I also want to reproduct it  agian, Thanks!

**Comment by knmnyn** [comment]
Hi @NLPOR Thanks for your comment.  The data is included in the original ParsCit distribution.  

See https://github.com/knmnyn/ParsCit/tree/master/crfpp/traindata

**Comment by NLPOR** [comment]
Thanks, the training data in your model is just&nbsp;https://github.com/knmnyn/ParsCit/tree/master/crfpp/traindata/tagged_reference.txt ? 500 samples?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Min-Yen Kan"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月6日(星期三) 下午2:53
收件人:&nbsp;"WING-NUS/Neural-ParsCit"<Neural-ParsCit@noreply.github.com&gt;;
抄送:&nbsp;"529379497"<529379497@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [WING-NUS/Neural-ParsCit] training data (#29)





 
Hi @NLPOR Thanks for your comment.  The data is included in the original ParsCit distribution.
 
See https://github.com/knmnyn/ParsCit/tree/master/crfpp/traindata
